# -*- coding: utf-8 -*-
"""Soil_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JmfQ00ZVXlbTu5udsi44xpTFUVsrLVIB
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Soil-data.csv')

print(df.shape)

print(df.columns)

df.head()

print(df.isnull().sum())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))

sns.countplot(
    x='Crop_Type',
    data=df
)

plt.title("Crop Type Distribution")

plt.xticks(rotation=0)

plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    x='Soil_Type',
    data=df
)

plt.title("Soil Type Distribution")

plt.xticks(rotation=0)

plt.show()

plt.figure(figsize=(6,4))

sns.countplot(
    x='Irrigation_Available',
    data=df
)

plt.title("Irrigation Availability Distribution")

plt.show()

plt.figure(figsize=(10,8))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Feature Correlation Heatmap")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(
    df['Soil_pH'],
    kde=True
)

plt.title("Soil pH Distribution")

plt.show()

plt.figure(figsize=(10,6))

sns.boxplot(data=df[['Soil_pH',
                     'Soil_Nitrogen',
                     'Rainfall',
                     'Temperature',
                     'Humidity']])

plt.title("Boxplot for Outlier Detection")

plt.show()

plt.figure(figsize=(10,5))

sns.countplot(x=y)

plt.title("Target Variable Distribution")

plt.show()

from sklearn.preprocessing import LabelEncoder

le_crop = LabelEncoder()
le_soil = LabelEncoder()

# Encode columns
df['Crop_Type'] = le_crop.fit_transform(df['Crop_Type'])

df['Soil_Type'] = le_soil.fit_transform(df['Soil_Type'])

# Define features and target
X = df.drop("Compatible", axis=1)
y = df["Compatible"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

"""**Classification Models**"""

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

rf_acc = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_acc)

from xgboost import XGBClassifier

xgb = XGBClassifier()

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

xgb_acc = accuracy_score(y_test, y_pred_xgb)

print("XGBoost Accuracy:", xgb_acc)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression(max_iter=500)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

lr_acc = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy:", lr_acc)

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

dt_acc = accuracy_score(y_test, y_pred_dt)

print("Decision Tree Accuracy:", dt_acc)

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

knn_acc = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:", knn_acc)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Store predictions in dictionary
predictions = {
    "Logistic Regression": y_pred_lr,
    "Decision Tree": y_pred_dt,
    "Random Forest": y_pred_rf,
    "KNN": y_pred_knn,
    "XGBoost": y_pred_xgb
}

# Plot confusion matrices
plt.figure(figsize=(15,12))

for i, (name, y_pred) in enumerate(predictions.items()):

    cm = confusion_matrix(y_test, y_pred)

    plt.subplot(3,2,i+1)

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues'
    )

    plt.title(name)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")

plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report

models_preds = {
    "Logistic Regression": y_pred_lr,
    "Decision Tree": y_pred_dt,
    "Random Forest": y_pred_rf,
    "KNN": y_pred_knn,
    "XGBoost": y_pred_xgb
}

for name, pred in models_preds.items():
    print("\n", name)
    print(classification_report(y_test, pred))

import matplotlib.pyplot as plt

models = ['LR','DT','RF','KNN','XGB']
accuracy = [lr_acc, dt_acc, rf_acc, knn_acc, xgb_acc]

plt.figure(figsize=(8,5))

plt.bar(models, accuracy)

plt.title("Classification Model Accuracy Comparison")

plt.xlabel("Models")

plt.ylabel("Accuracy")

plt.show()

"""**Clustering**"""

from sklearn.cluster import KMeans

# Select numeric columns only
X_cluster = df.select_dtypes(include=['float64','int64'])

kmeans = KMeans(
    n_clusters=3,
    random_state=42
)

clusters = kmeans.fit_predict(X_cluster)

df['Cluster'] = clusters

print(df['Cluster'].value_counts())

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

wcss = []

for i in range(1,11):

    kmeans = KMeans(
        n_clusters=i,
        random_state=42
    )

    kmeans.fit(X_cluster)

    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(1,11), wcss, marker='o')

plt.title("Elbow Method for Optimal Clusters")

plt.xlabel("Number of Clusters")

plt.ylabel("WCSS")

plt.show()

plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df['Temperature'],
    y=df['Rainfall'],
    hue=df['Cluster']
)

plt.title("KMeans Clustering Based on Temperature and Rainfall")

plt.show()

from scipy.cluster.hierarchy import dendrogram, linkage
import matplotlib.pyplot as plt

X_cluster = df.select_dtypes(include=['float64','int64'])

linked = linkage(X_cluster, method='ward')

plt.figure(figsize=(10,6))

dendrogram(linked)

plt.title("Hierarchical Clustering Dendrogram")

plt.xlabel("Data Points")

plt.ylabel("Distance")

plt.show()

from sklearn.cluster import AgglomerativeClustering

hc = AgglomerativeClustering(
    n_clusters=3
)

df['HC_Cluster'] = hc.fit_predict(X_cluster)

print(df['HC_Cluster'].value_counts())

plt.figure(figsize=(8,5))

sns.scatterplot(
    x=df['Temperature'],
    y=df['Rainfall'],
    hue=df['HC_Cluster']
)

plt.title("Hierarchical Clustering Visualization")

plt.show()

"""**ANN (Artificial Neural Network)**"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# ANN Model
ann = Sequential()

ann.add(Dense(
    64,
    activation='relu',
    input_shape=(X_train.shape[1],)
))

ann.add(Dense(32, activation='relu'))

ann.add(Dense(len(set(y)), activation='softmax'))

ann.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train ANN
history_ann = ann.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test, y_test)
)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(history_ann.history['accuracy'])
plt.plot(history_ann.history['val_accuracy'])

plt.title("ANN Model Accuracy")

plt.xlabel("Epochs")

plt.ylabel("Accuracy")

plt.legend(['Train','Validation'])

plt.show()

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# DNN Model
dnn = Sequential()

dnn.add(Dense(
    128,
    activation='relu',
    input_shape=(X_train.shape[1],)
))

dnn.add(Dense(64, activation='relu'))

dnn.add(Dense(32, activation='relu'))

dnn.add(Dropout(0.3))

dnn.add(Dense(len(set(y)), activation='softmax'))

dnn.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train DNN
history_dnn = dnn.fit(
    X_train,
    y_train,
    epochs=25,
    batch_size=32,
    validation_data=(X_test, y_test)
)

plt.figure(figsize=(8,5))

plt.plot(history_dnn.history['accuracy'])
plt.plot(history_dnn.history['val_accuracy'])

plt.title("DNN Model Accuracy")

plt.xlabel("Epochs")

plt.ylabel("Accuracy")

plt.legend(['Train','Validation'])

plt.show()

ann_acc = max(history_ann.history['val_accuracy'])
dnn_acc = max(history_dnn.history['val_accuracy'])

models = ['ANN','DNN']
accuracy = [ann_acc, dnn_acc]

plt.figure(figsize=(6,4))

plt.bar(models, accuracy)

plt.title("ANN vs DNN Accuracy Comparison")

plt.ylabel("Accuracy")

plt.show()

import joblib

# Save Random Forest model
joblib.dump(
    rf,
    "/content/drive/MyDrive/crop_prediction_model.pkl"
)

print("Model saved successfully!")

joblib.dump(
    le_crop,
    "/content/drive/MyDrive/crop_label_encoder.pkl"
)

joblib.dump(
    le_soil,
    "/content/drive/MyDrive/soil_label_encoder.pkl"
)

print("Encoders saved!")

